import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore, doc, getDocFromServer } from 'firebase/firestore';

// We import the config. If it doesn't exist yet, we'll use a placeholder
// to prevent the app from crashing during development while the user
// sets up Firebase via the tool.
let firebaseConfig = {};

try {
  // @ts-ignore - This file is generated by the set_up_firebase tool
  import('../../firebase-applet-config.json').then(config => {
    firebaseConfig = config.default;
  }).catch(() => {
    console.warn("Firebase configuration not found. Please run the 'set_up_firebase' tool.");
  });
} catch (e) {
  console.warn("Firebase configuration not found. Please run the 'set_up_firebase' tool.");
}

// Default empty config to prevent crash if not yet set up
const config = {
  apiKey: "placeholder",
  authDomain: "placeholder",
  projectId: "placeholder",
  storageBucket: "placeholder",
  messagingSenderId: "placeholder",
  appId: "placeholder",
  ...firebaseConfig
};

const app = initializeApp(config);

// @ts-ignore
export const db = getFirestore(app, config.firestoreDatabaseId);
export const auth = getAuth(app);

async function testConnection() {
  try {
    await getDocFromServer(doc(db, 'test', 'connection'));
  } catch (error) {
    if(error instanceof Error && error.message.includes('the client is offline')) {
      console.error("Please check your Firebase configuration.");
    }
  }
}

if (config.apiKey !== "placeholder") {
  testConnection();
}
